### ISSUE TITLE
Missing prefabs and and unlinked tooltips

### ISSUE THREAD

**Issue by CubicVR** [provencher/MRTK-Quest#42]
Couple of minor missing bits:
- All "PressableButtonHoloLens2ToggleRadio" prefabs are missing under "RadioGroup96x32" in "MRTK-Quest_Development" scene
- "EarthCore" object is missing tooltip links in On Manipulation events in both sample scenes.

**Comment by provencher** [comment]
Thanks for your issue @CubicVR 

>     * All "PressableButtonHoloLens2ToggleRadio" prefabs are missing under "RadioGroup96x32" in "MRTK-Quest_Development" scene

Not the case on my end:
![image](https://user-images.githubusercontent.com/7420990/77090571-bc88eb00-69dd-11ea-82d9-95e283f130fb.png)

Th the new pressable buttons require fairly recent MRTK dev branch. If you are not using the submodule method for MRTK, this will result in missing prefabs.

>     * "EarthCore" object is missing tooltip links in On Manipulation events in both sample scenes.
This is true in the MRTK dev scene - due to the migration to ObjectManipulator.
In the 2.3 scene however, it seems to be well setup on my end.
![image](https://user-images.githubusercontent.com/7420990/77090876-299c8080-69de-11ea-9bb1-4637045b5b8f.png)

**Comment by CubicVR** [comment]
Thanks for the clarification on the Dev Branch and upon checking again, you are correct, 2.3 scene has tooltips set up fine.
