### ISSUE TITLE
CheckCapability always return true

### ISSUE THREAD

**Issue by AlexisAG** [provencher/MRTK-Quest#43]
Actualy **CheckCapability** of **OculusQuestInputManager** always returns true when we're trying to find out if HandTracking is enabled.
```
public bool CheckCapability(MixedRealityCapability capability)
{
  return (capability == MixedRealityCapability.ArticulatedHand);
}
```

So, if we want a specific behavior **without** hand tracking, this is not possible (via mrtk profile). 
Maybe an _Option Enable Hand_ Tracking should be exposed in the **OculusQuestInputManager** ?

**Comment by provencher** [comment]
The reason it's like that is because of Avatar hands.

Avatar hands are like emulated hand tracking, and they have fully mapped joints, and support poke and hand menus and everything hands do. 

Also I cannot expose the settings for Hand Tracking in Oculus because the scriptable objects those settings exist in are not in the OculusVR assembly, which means MRTK-Quest cannot see them.

The only way to turn off hand tracking is to do so with the Oculus Build Settings scriptable object, which I discussed in the FAQ of the Readme.

Another note - for settings where you want to change behavior, check the MRTKQuest Config Scriptable object. Its in the ressources folder.
