### ISSUE TITLE
PokePointer for every finger

### ISSUE THREAD

**Issue by crodriguezouterelo** [provencher/MRTK-Quest#48]
Hi! Great repositorie, I have been tinkering with it for a while now.
However, I have not yet managed to make the PokePointer element work with every finger. 
What am I missing? It should be easy to implement as each finger has its own skeleton with iterable names.

I have also tried to use the HandsManager prefab from the Oculus Framework along with the InteractableToolsSDKDriver. While my try found no avail, perhaps you could use these controllers to define the position of new PokePointer elements.

Sorry for the inconvenience and thanks in advance.

**Comment by provencher** [comment]
Hi @crodriguezouterelo!

Thanks for reaching out about this.
Poke pointers for every finger is an interesting topic. Through personal experimentation, it’s not the best idea since you end up accidentally pressing buttons more often than it adds value.

Microsoft have done research making similar findings as well.

That said, if you feel particular strongly about the possibility of doing this, I recommend making a feature request on the official MRTK repo, as this is a limitation of the framework as a whole.

Best of luck creating with MRTK-Quest!
Eric

**Comment by crodriguezouterelo** [comment]
Hi @provencher! Thank you for your quick response.

While I can easily imagine the issues you were running into, I guess it depends on how the buttons are built (their position, size, depth...). I also find the idea of allowing the PokePointer to work with different fingers than just the index interesing (say, for example, the virtual simulation of a thumbprint).

Since you have already tried to make this work, perhaps you could lend me a helping hand: what is it you tweaked to make the PokePointer element to follow the rest of the fingers?

As per your suggestion, I will also be posting this issue in the MRTK repo.
Thanks for the help so far!

**Comment by provencher** [comment]
@crodriguezouterelo as far as MRTK-Quest is concerned, [here ](https://github.com/provencher/MRTK-Quest/blob/master/Assets/MixedRealityToolkit.ThirdParty/MRTK-Quest/Scripts/Input/Controllers/OculusQuestHand.cs) is where the fingertip cursor is set:
![image](https://user-images.githubusercontent.com/7420990/81565147-e7047e00-9366-11ea-9f8d-72082ed86c3a.png)

Would it help your usecase to be able to control what finger the cursor appears on? I wanted to remain consistent with HL2, but if you have a real usecase, I can expose an enum that allows you to control that. Still, I can't make it so that more than 1 finger per hand is supported - that's an MRTK limitation.

**Comment by crodriguezouterelo** [comment]
Alright, thank you for the heads up!
An enum would be nice, indeed. I guess I can get the PokePointer to follow the thumb by changing the TrackedHandJoint element, but it is always nice to have a non-coding way to change these things.

Again, thank you for your help! :)

**Comment by provencher** [comment]
I looked into this, and I think your feedback is better served on the official MRTK github @crodriguezouterelo. Going to close this for now.
