### ISSUE TITLE
Hand tracking feature is not working in Oculus Quest Headset.....

### ISSUE THREAD

**Issue by castana1962** [provencher/MRTK-Quest#87]
Hi All,
I am trying the MRTK-Quest_Development Scene through Unity and Quest by Oculus Link Cable and I saw the hand tracking feature successfully of this way, but after that; I built this one to see it in my Oculus Quest( without any Link cable). It was built "successfully". After I opened the App in my Headset and I cannot see the Hands Tracking( This feature is enable in my Quest Headset). Then I tried it again, and I got a message that "to see this app, I have to change to Controllers feature", for that reason, Could anybody help me to fix it?
Thanks for your time
Regards
Alejandro

**Comment by Acimaz** [comment]
Hey castana,

this is because the camera prefab which is used for MRTK Quest hast set the hand tracking support to hands and controller or just controller. 

If you want to start the app without controller at all you have to change this setting. Inside unity search for the asset "camerarig". Unity will show you two results. Go ahead and change the setting on those assets inside the OVRManager to "Hands only". I attached a screenshot to show you which setting I mean.

![image](https://user-images.githubusercontent.com/3418387/91184019-6c305a80-e6ec-11ea-9dfe-0d891ae05f8a.png)

**Comment by castana1962** [comment]
Hi Acimaz,
Thanks for your help one more time and sorry for my mistake
Regards
Alejandro

**Comment by Acimaz** [comment]
No need to be sorry. You are welcome!

**Comment by provencher** [comment]
Thanks for helping resolve this @Acimaz
