### ISSUE TITLE
BaseControllerPointer.cs Error Quest MRTK or MRTK?

### ISSUE THREAD

**Issue by JShull** [provencher/MRTK-Quest#88]
## Null Reference Exception

* I think this is a joint issue with general MRTK but I realized that it's activated by OculusQuestInputManagers.cs which is MRTK-Quest related.

### Steps to Reproduce

* While tethered to the PC running Oculus Link in Unity's Editor
* This only seems to happen when I go from a transition between pulling the headset up on my head and pulling it back down while simultaneously having my hands being captured. 

### What I think is going on & Quick Fix

* Line 475 on BaseControllerPointer.cs throws a null reference exception error 
* 'InputSourceParent' hasn't been established yet thus throwing the exception. 
* If a null reference check is added on the BaseControllerPointer.cs before InputSourceParent is referenced the error goes away

#### Image of Unity Debugger & Fix

![image](https://user-images.githubusercontent.com/12342337/91328668-35624f00-e795-11ea-81e1-b404cfac3a4d.png)
![image](https://user-images.githubusercontent.com/12342337/91328885-7e1a0800-e795-11ea-9778-a3b4bc293baa.png)

**Comment by provencher** [comment]
As you mentioned, this is a bug report for MRTK, not for MRTK-Quest. Please file that report on their github.

If you have a fix that can avoid it on MRTK-Quest without touching the MRTK code, I'm open to that, but there's not much I can do otherwise. Thanks.

**Comment by keveleigh** [comment]
>transition between pulling the headset up on my head and pulling it back down while simultaneously having my hands being captured.

This feels like a bug in the implementation here. I can't recall seeing this case in any of the MRTK-defined device managers, but maybe we have a race condition that only shows up in a specific case.

~Why would the source be lost (or maybe back-to-back found and lost) when the headset is pulled back down? It seems like hand tracking should be successful at that point.~

I think that might be a red herring though. An input source should exist for as long as the controller exists, and an input source is required _for_ a controller to exist. It's not a Unity object, so there's no chance of it being destroyed from the scene. How is it null? Since this is happening in the Editor, it should be pretty easy to run a debugger against to check (I don't have a Quest, or I'd try), or even just add some `Debug.Log`s to see when / how often RemoveHandDevice is called.

The following code grabs a generic input source and sets it on the pointers. It appears to run on Unity's `Update` loop, so I can't think of a reason it'd be running out-of-sync with a lost event:

https://github.com/provencher/MRTK-Quest/blob/896d2e1639b571c6d177cac143259cd1094aa867/Assets/MRTK.ThirdParty/MRTK-Quest/Scripts/Input/DeviceManager/OculusQuestInputManager.cs#L370-L387

After digging in a bit more, I thought it might be based on the device manager firing multiple lost events for the same hand, but I can't find the exact path to support this theory:

1. RemoveHandDevice is called
1. `RecyclePointers` is called, which calls `Reset`, which sets the `Controller` to null https://github.com/microsoft/MixedRealityToolkit-Unity/blob/33781c0bcebbcb5f9c0df9160f13db300e13cc27/Assets/MRTK/SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs#L406-L412
    1. This is where my theory falls apart, I think, since the `Controller` setter won't change `InputSourceParent` unless the new value is non-null
1. RemoveHandDevice is called a second time
1. InputSourceParent is null due to the previous recycling / cleaning up of pointers?

**Comment by keveleigh** [comment]
All that being said, I'm not fully against just adding that null check to fix things, but it feels like it might be hiding either an invalid set-up or a case we need to explicitly handle another way (recycled pointers that are still getting events but shouldn't be? not sure)

**Comment by JShull** [comment]
Let me try removing that null check and dump you the full log and see if that helps - will add this towards my items for tomorrow and will follow back up to provide the best information I can.

**Comment by keveleigh** [comment]
@JShull Appreciate it!

**Comment by JShull** [comment]
Here's what I noticed:

The error throws three times - all point to the same BaseControllerPointer.cs Line 475, but the second error of the three has a slightly different path, right before BaseControllerPointer.cs it is coming from PokePointer.cs 460... is this the missing path?

Here's the updated images from Unity on the NullReference Exception (this time all three of them)

![image](https://user-images.githubusercontent.com/12342337/91948100-be194780-eccd-11ea-8912-47b1110283f1.png)

![image](https://user-images.githubusercontent.com/12342337/91948294-d25d4480-eccd-11ea-82ec-463de9c8b937.png)

![image](https://user-images.githubusercontent.com/12342337/91948443-db4e1600-eccd-11ea-97e9-8154f0a3203a.png)

Also noticed this go around at the end some 'task.rasterData.vertexBuffer = = NULL' was thrown not sure if that's related or just fall out from the other errors.

Hope this helps!
